site: Rajesh's Blog
url: https://mrprajesh.github.io
title: Rajesh's Blog
description: Writing down my random thoughts
twitter:
  username: #mrprajesh
  card: summary
  creator: #mrprajesh
author:
  twitter: #mrprajesh
  name: #Rajesh Pandian M
  avatar:
  email:
  url: #https://mrprajesh.github.io
  permalink:

baseurl: "/blog"
timezone: Asia/Kolkata

exclude:
  - .jekyll-cache

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]

sass:
  sass_dir:          _sass
  style:            :compressed

plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  pages:
    output: true
    permalink: /:name.html
  posts:
    output: true
    permalink: /:slug.html
    #permalink: /:year/:month/:day/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
